Natooz/MidiTok

miditok/midi_tokenizer_base.py
The current version of the function does not work well with midi paths with directories with them in python notebooks, this is because a directory has to created before a file can be stored. For example, if the midi path is `a/b/c.mid`,  and the output directory is `d/e` then the code gives an error unless `d/e/a/b/` directory exists. 
<br/>
This PR will automatically take the name of the MIDI file and saves it in the directory as `d/e/c.json`. There is a commented code in line 239 if we want to concatenate the entire path as `d/e/a/b/c.mid.json`
=> Ms3744 patch tokenize dataset

miditok/cp_word.py, miditok/midi_like.py, miditok/midi_tokenizer_base.py, miditok/mumidi.py, miditok/octuple.py, miditok/octuple_mono.py, miditok/remi.py, miditok/structured.py
Hi, thanks for the great repository! I plan to use it for my research purposes, so probably, this is not my last pull request :) 
I have been playing around with the encodings and, after code profiling, I found a few computational bottlenecks in `midi_to_tokens`:
1. Encoding of `Duration`/`Time-Shift` tokens
2. Quantization of `Velocity`
3. Quantization of `Tempo`
List comprehensions (especially for durations) take more than half of the computation time of `midi_to_tokens`. Since NumPy is one of the library dependencies, it is beneficial to utilize it instead of pure Python code. Hopefully, I covered all relevant cases.
The overall speedups for different tokenizations might range from a few percent to x2-3. For example, the tests (with much other stuff) run x1.5 faster on my setup.
=> Speed up midi_to_tokens

miditok/constants.py, miditok/midi_tokenizer_base.py, miditok/octuple.py, tests/tests_multitrack.py, tests/tests_one_track.py, tests/tests_utils.py
Hi! Here is some contribution to MidiTok: time signature changes and tokens!
Time Signatures are listed as TODO in readme. I don't know the current status, but I would love to share my almost complete implementation for a review. I work with OctupleMIDI encoding and music primarily not in 4/4, so I implemented the core time signature processing and support for `TimeSignature` tokens in `Octuple` encoding.
I used MusicBERT's Octuple encoding as a reference. Time signature vocabulary is constructed similarly to the process introduced in MusicBERT [paper](https://arxiv.org/pdf/2106.05630.pdf) and [code](https://github.com/microsoft/muzic/blob/main/musicbert/preprocess.py#L57-L62) for Octuple encoding. Time signature reduction is also borrowed from MusicBERT.
The current code supports …
=> [WIP] Time signature tokens

colab-notebooks/Full_Example_HuggingFace_GPT2_Transformer.ipynb
just fixed the bug in "Generate Music" as following:
```
ValueError: If `eos_token_id` is defined, make sure that `pad_token_id` is defined.
```
added pad_token_id definition in GenerationConfig.
=> Fix the "no pad_token_id" bug in generation

README.md, docs/citations.rst, docs/midi_tokenizer.rst, docs/tokenizations.rst, miditok/__init__.py, miditok/constants.py, miditok/midi_tokenizer.py, miditok/tokenizations/__init__.py, miditok/tokenizations/mmm.py, miditok/tokenizations/remi_plus.py, tests/test_bpe.py, tests/test_methods.py, tests/test_multitrack.py, tests/test_one_track.py
=> Adding MMM tokenizer

miditok/midi_tokenizer.py, tests/test_one_track.py
This change addresses a bug in `MIDITokenizer.__repr__`, which causes the code to crash when attempting to print a `MIDITokenizer` for which `tokenizer.is_multi_voc == False`.
A minimal working example of this bug:
```
>>> from miditok import REMI
>>> print(REMI())
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/home/dt/code/scratch/MidiTok/miditok/midi_tokenizer.py", line 1877, in __repr__
f'{len(self.len)} tokens {"(multi-voc) " if self.is_multi_voc else ""}'
^^^^^^^^^^^^^
TypeError: object of type 'int' has no len()
```
Note that the output string for tokenizers with multiple vocabularies is now different than it was previously. Previously:
```
>>> from miditok import Octuple
>>> print(Octuple())
6 tokens (multi-voc) without BPE
```
and now:
```
>>> from …
```
=> Fix MIDITokenizer.__repr__ and test

miditok/utils/utils.py, tests/test_utils.py
[miditoolkit's `PitchBend`](https://github.com/YatingMusic/miditoolkit/blob/9835be29e42fbc23529d61273820707ccfa189f4/miditoolkit/midi/containers.py#L54-L71) has no attribute `start`, this PR fixes the bug in `merge_tracks` function.
=> Fix PitchBend time attribute

README.md, docs/midi_tokenizer.rst, miditok/__init__.py, miditok/classes.py, miditok/constants.py, miditok/data_augmentation/data_augmentation.py, miditok/midi_tokenizer.py, miditok/tokenizations/cp_word.py, miditok/tokenizations/midi_like.py, miditok/tokenizations/mmm.py, miditok/tokenizations/mumidi.py, miditok/tokenizations/octuple.py, miditok/tokenizations/octuple_mono.py, miditok/tokenizations/remi.py, miditok/tokenizations/remi_plus.py, miditok/tokenizations/structured.py, miditok/tokenizations/tsd.py, miditok/utils/utils.py, setup.py, tests/benchmark_fast_bpe.py, tests/test_bpe.py, tests/test_multitrack.py, tests/test_one_track.py, tests/test_saving_loading_config.py, tests/test_utils.py
This PR adds a `TokenizerConfig` class that holds the common parameters of all tokenizers, such as `beat_res`, `nb_velocities` or the entries of the previous `additional_tokens` attribute.
This object is hold by tokenizers as a `.config` attribute.
It greatly simplifies the way to instantiate tokenizers, as well as saving and loading their parameters.
`save_params` overrides are also removed, allowing a uniformisation of tokenizer parameters saving and loading. `load_params` is still compatible with previous versions (< v2.1.0).
=> New TokenizerConfig object, and method to instantiate tokenizers

docs/examples.rst
Small typo in tokenizer config "pitch_range" parameter
=> Fix typo in tokenizer example

miditok/classes.py, miditok/constants.py, miditok/midi_tokenizer.py, miditok/tokenizations/cp_word.py, miditok/tokenizations/midi_like.py, miditok/tokenizations/mmm.py, miditok/tokenizations/mumidi.py, miditok/tokenizations/octuple.py, miditok/tokenizations/octuple_mono.py, miditok/tokenizations/remi.py, miditok/tokenizations/remi_plus.py, miditok/tokenizations/tsd.py
Hi! This PR adds support for log scale tempos in addition to the existing linear scale tempos. Log scale tempos are used by [MusicBERT](https://github.com/microsoft/muzic/tree/main/musicbert) and maybe some other works.
I made the tempo values as rounded floats because rounding to integers can result in repeated values for certain configurations (low `min_tempo` and large `nb_tempos`) and loss of precision for differences/ratios between neighbouring values.
=> Configure tempo values scale

miditok/classes.py, miditok/constants.py, miditok/midi_tokenizer.py, miditok/tokenizations/cp_word.py, miditok/tokenizations/mmm.py, miditok/tokenizations/mumidi.py, miditok/tokenizations/octuple.py, miditok/tokenizations/octuple_mono.py, miditok/tokenizations/remi.py, tests/benchmark_fast_bpe.py, tests/test_bpe.py, tests/test_io_formats.py, tests/test_multitrack.py, tests/test_one_track.py, tests/test_saving_loading_config.py
This PR:
* changes `time_signature_range` into a dictionary `{denom_i: [num_i1, ..., num_in] / (min_num_i, max_num_i)}`;
* `MIDITokenizer`: remove `_reduce_time_signature()` and add `validate_midi_time_signatures()` to require users to specify all needed time signatures before tokenizer construction and to allow checking if MIDI has any unsupported ones (also used in `tokenize_midi_dataset()`);
* updates tokenizers' code where time signatures and `ticks_per_bar` are computed;
* updates `time_signature_range` in test files.
=> Update time signature tokens configuration

miditok/classes.py, miditok/constants.py, miditok/midi_tokenizer.py, miditok/tokenizations/cp_word.py, miditok/tokenizations/midi_like.py, miditok/tokenizations/mmm.py, miditok/tokenizations/mumidi.py, miditok/tokenizations/octuple.py, miditok/tokenizations/remi.py, miditok/tokenizations/structured.py, miditok/tokenizations/tsd.py, setup.py, tests/benchmark_fast_bpe.py, tests/test_bpe.py, tests/test_io_formats.py, tests/test_multitrack.py, tests/test_one_track.py, tests/test_saving_loading_config.py, tests/tests_utils.py
=> one_token_stream_for_programs config param and successive TimeShift tokens

miditok/classes.py, miditok/constants.py, miditok/midi_tokenizer.py, miditok/tokenizations/cp_word.py, miditok/tokenizations/midi_like.py, miditok/tokenizations/mmm.py, miditok/tokenizations/mumidi.py, miditok/tokenizations/octuple.py, miditok/tokenizations/remi.py, miditok/tokenizations/structured.py, miditok/tokenizations/tsd.py, miditok/utils/utils.py, setup.py, tests/test_io_formats.py, tests/test_multitrack.py, tests/test_one_track.py, tests/tests_utils.py
Following #71, this PR adds the option (`config.program_changes`) to use `Program` tokens similarly to the way the MIDI `Program Change` messages occur.
The option only works for `TSD`, `REMI` and `MIDILike` as multi-voc tokenizers will gather the Program information with the note tokens, program changes would break `Structured`'s recurrent token type succession, and `MMM` already separate the tracks within the token sequence.
Still a few things to check, and enforce the multitrack tests
=> Multitrack ProgramChange

docs/tokenizations.rst, miditok/tokenizations/cp_word.py, miditok/tokenizations/remi.py, tests/test_one_track.py
Following #73, this PR fixes a bug in `REMI` and `CPWord` where the first Time Signature (when at tick 0) was ignored and replaced by the default one (4/4).
=> Fixing time signature error for REMI and CPWord (first TS at tick 0)

miditok/pytorch_data/datasets.py, tests/test_pytorch_data_loading.py
Following #78, this PR adds the ability to read labels from `DatasetTok` with a `func_to_get_labels` provided method.
@leleogere you can review if desired before merging the PR. Otherwise I'll merge in a few days :)
=> Adding func_to_get_labels argument to DatasetTok

miditok/utils/utils.py
Following #77 , this PR fixes a bug in `miditok.utils.detect_chords` that raised errors when the user did not specified to use unknown chords
=> fix in detect_chords: bad check when not using unknown chords

miditok/pytorch_data/collators.py, tests/test_pytorch_data_loading.py
Following #80, this PR fixes a bug in DataCollator when handling classification labels (tensors with 0 dimensions).
@leleogere
=> Fix in DataCollator for classification labels

miditok/__init__.py, miditok/constants.py, miditok/data_augmentation/data_augmentation.py, miditok/midi_tokenizer.py, miditok/pytorch_data/collators.py, miditok/pytorch_data/datasets.py, miditok/tokenizations/cp_word.py, miditok/tokenizations/midi_like.py, miditok/tokenizations/mmm.py, miditok/tokenizations/octuple.py, miditok/tokenizations/remi.py, miditok/tokenizations/structured.py, miditok/tokenizations/tsd.py, setup.py, tests/test_bpe.py, tests/test_methods.py, tests/test_pytorch_data_loading.py
Following #79, this PR make `tokenize_midi_dataset` reproduce the source files file tree in `out_dir`.
It also allows to handle file overwriting if files already exist in the saving path.
The file tree reproduction has also to be made for `data_augmentation_dataset`
=> tokenize_midi_dataset reproducing source file tree, overwrite_mode

miditok/midi_tokenizer.py, miditok/tokenizations/midi_like.py, miditok/tokenizations/structured.py, miditok/utils/utils.py
This pull request fixes typos in function helper text. Following are the fixed typos:
1. objet -> object
2. regarless -> regardless
I kindly request the repository maintainers to review and merge it. Thanks! :heart:
=> fix typos in python function helper texts

miditok/midi_tokenizer.py, requirements.txt, setup.py, tests/test_bpe.py, tests/test_methods.py, tests/test_one_track.py, tests/tests_utils.py
=> Fixing a bug when learning bpe without special tokens

miditok/midi_tokenizer.py
Fixes #131 
In `_preprocess_time_signatures`, the `ticks_per_bar` computations were made based on the tokenizer's time division instead of the MIDI's, which can be different depending on the time signatures in the MIDI and those supported by the tokenizer, resulting in erroneously shifted time signatures.
Now the MIDI's time signature is passed to `_preprocess_time_signatures `.
----
📚 Documentation preview 📚: https://miditok--132.org.readthedocs.build/en/132/
=> Fixing time signature preprocessing (time division mismatch)

miditok/midi_tokenizer.py, tests/test_bpe.py
Following #137 , this PR makes sure the `TokSequence` in input of `tokens_to_midi` is automatically preprocessed: `tokens` have been completed, does it if necessary, and decode BPE if necessary
----
📚 Documentation preview 📚: https://miditok--138.org.readthedocs.build/en/138/
=> decoding: automatically making sure to decode BPE then completing `tokens`

miditok/classes.py, miditok/midi_tokenizer.py, tests/test_saving_loading_config.py
As mentioned in #137, this PR makes the `load_tokens` method automatically return `TokSequence` objects. Tests for this have been added.
----
📚 Documentation preview 📚: https://miditok--139.org.readthedocs.build/en/139/
=> `load_tokens` now returning `TokSequence`

miditok/midi_tokenizer.py
Hi,
I encountered an issue with chord maps when loading a saved tokenizer configuration from a file. 
The CHORD_MAPS constant value has each chord map defined in a tuple, but after creating a tokenizer and saving the configuration, the chord maps are represented as lists (example snippet below):
```
...
"chord_maps": {
"min": [
0,
3,
7
],
"maj": [
0,
4,
7
],
...
"9min": [
0,
4,
7,
10,
13
]
},
...
```
This is caused by [json.dump](https://github.com/Natooz/MidiTok/blob/main/miditok/midi_tokenizer.py#L2778-L2779) converting all tuples into lists. This results in the [detect_chords](https://github.com/Natooz/MidiTok/blob/main/miditok/utils/utils.py#L243-L253) function always returning ukn chord tokens, i.e. 'Chord_A:ukn3', 'Chord_E:ukn3', etc.
There are a few ways to fix this:
- Make sure …
=> convert chord maps back to tuples from list when loading tokenizer from a saved configuration

.github/workflows/pytest.yml, README.md, docs/conf.py, miditok/midi_tokenizer.py, pyproject.toml, tests/test_hf_hub.py
Following #127, this PR adds a way to dynamically instantiate a tokenizer solely based on a configuration file.
For example, using `MIDITokenizer.from_pretrained(config_path)` is now similar to `TSD.from_pretrained(config_path)` if the config file was saved from a `TSD` tokenizer.
----
📚 Documentation preview 📚: https://miditok--142.org.readthedocs.build/en/142/
=> can now use `MIDITokenizer.from_pretrained` similarly to `AutoTokenizer`

colab-notebooks/Example_HuggingFace_Mistral_Transformer.ipynb
Hi, I was running this example notebook locally, which didn't work until introducing these two small fixes. So I propose a change for your consideration. Thanks!
----
📚 Documentation preview 📚: https://miditok--145.org.readthedocs.build/en/145/
=> Fix token_paths to files_paths, and config to model_config

miditok/tokenizations/cp_word.py, miditok/tokenizations/octuple.py, miditok/tokenizations/remi.py
Hi! I've been playing around with miditok>3.0.0 and found two bugs in the Octuple encoding:
1. Octuple tokenizer with multiple time signatures with different beat values (e.g., `time_signature_range = {2: (1, 2), 4: (1, 4), 8: (1, 8)}`) encodes and decodes positions so that they are shorter than in the original MIDI. For example, note positions in */4 bars are decoded twice as short within the bar. The example MIDI in #131 will not be decoded correctly if there is a time signature */8 in the config.
_Solution_: adapt the position encoding logic from REMI to Octuple.
2. The duration of the first note after the time signature change might be encoded incorrectly.
_Solution_: move the processing of time signatures above the note duration.
----
📚 Documentation preview 📚: …
=> Fix issues in Octuple with multiple different-beat time signatures

README.md, miditok/tokenizations/midi_like.py, miditok/tokenizations/mmm.py, miditok/tokenizations/remi.py, miditok/tokenizations/tsd.py
----
📚 Documentation preview 📚: https://miditok--149.org.readthedocs.build/en/149/
=> Pitch interval decoding: discarding notes outside the tokenizer pitch range

miditok/midi_tokenizer.py, tests/test_hf_hub.py
Since [`huggingface_hub` v0.21](https://github.com/huggingface/huggingface_hub/releases/tag/v0.21.0) `ModelHubMixin.save_pretrained` will automatically save ``self.config`` after calling ``self._save_pretrained``, which is unnecessary in our case as ``self._save_pretrained`` already saves the tokenizer's config.
This PR overrides `ModelHubMixin.save_pretrained` to get rid of the config logic.
----
📚 Documentation preview 📚: https://miditok--150.org.readthedocs.build/en/150/
=> Fixing `save_pretrained` to comply with huggingface_hub v0.21

miditok/midi_tokenizer.py
Updated from the previous PR. This just updates _create_durations_tuples allowing it to be overridden by the child class. 
----
📚 Documentation preview 📚: https://miditok--153.org.readthedocs.build/en/153/
=> ability to overwrite _create_durations_tuples in init

README.md, docs/pytorch_data.rst, miditok/midi_tokenizer.py
Fixing incorrect model __repr__ when loading a tokenizer from a file (not reporting the model's name)
----
📚 Documentation preview 📚: https://miditok--165.org.readthedocs.build/en/165/
=> `_model_name` is now a protected property

miditok/pytorch_data/datasets.py
If pre-tokenizing the dataset for training, the bug forces us to have func_to_get_labels.
----
📚 Documentation preview 📚: https://miditok--170.org.readthedocs.build/en/170/
=> small bug fix in MIDI pretokenization

miditok/midi_tokenizer.py
----
📚 Documentation preview 📚: https://miditok--172.org.readthedocs.build/en/172/
=> adding `no_preprocess_score` argument when tokenizing

miditok/tokenizer_training_iterator.py
----
📚 Documentation preview 📚: https://miditok--183.org.readthedocs.build/en/183/
=> making sure MMM token sequences are not concatenated when splitting them per bar/beat in tokenizer_training_iterator.py

benchmarks/tokenizer_training/benchmark_training.py, docs/examples.rst, docs/train.rst, miditok/classes.py, miditok/midi_tokenizer.py, miditok/tokenizations/__init__.py, miditok/tokenizations/midi_like.py, miditok/tokenizations/mumidi.py, miditok/tokenizations/structured.py
Fix the Dataset and collator example code block, the implementation of which was bugged.
- Need to instantiate the tokenizer
- Can't pass a positional argument after a keyword argument
Fix rST backtick errors which open with two backticks and close with one backtick.
Fix rST code markup with single backticks to use double backticks instead.
----
📚 Documentation preview 📚: https://miditok--184.org.readthedocs.build/en/184/
=> rST Documentation fixes

tests/test_hf_hub.py
----
📚 Documentation preview 📚: https://miditok--199.org.readthedocs.build/en/199/
=> fix import HfHubHTTPError with latest hf hub package update

.github/workflows/pytest.yml, pyproject.toml
So that xdist don't assign chunks of training tests to the same worker, we use the `--dist worksteal` distribution mode to dynamically reassign queued tests to free workers.
----
📚 Documentation preview 📚: https://miditok--201.org.readthedocs.build/en/201/
=> Using --dist worksteal for tests distribution among workers

docs/pytorch_data.rst
Instead, put split_files_for_training
----
📚 Documentation preview 📚: https://miditok--205.org.readthedocs.build/en/205/
=> Remove refs to split_midis_for_training in doc

src/miditok/midi_tokenizer.py
Fixing a bug where a tokenizer training discarded tokens present from the base vocabulary but not in the training data.
----
📚 Documentation preview 📚: https://miditok--220.org.readthedocs.build/en/220/
=> bugfix training initial alphabet

src/miditok/data_augmentation/data_augmentation.py
Hi!
This pull request introduces a new parameter 'augment_copy' to the augment_score function in the data_augmentation module. This enhancement provides users with more control over how the augmentation is applied to the input Score object.
Changes made:
1. Added a new boolean parameter 'augment_copy' with a default value of True.
2. Updated the function's docstring to include a description of the new parameter.
3. Modified the function logic to use the 'augment_copy' parameter when deciding whether to create a copy of the input Score object or modify it in-place.
The 'augment_copy' parameter allows users to choose between two behaviors:
- When True (default): A copy of the input symusic.Score object is augmented and returned, preserving the original object.
- When False: The input …
=> Add a parameter augment_copy to the augment_score function

.github/workflows/publish-pypi.yml, .github/workflows/pytest.yml, pyproject.toml
Fixing build error due to bad target path since the change to the "src" project structure, reported in #222 
----
📚 Documentation preview 📚: https://miditok--223.org.readthedocs.build/en/223/
=> Fixing build target + using hatch in github actions

src/miditok/tokenizations/pertok.py, tests/test_saving_loading_config.py
Hi, this PR fixes the issue I describe here: https://github.com/Natooz/MidiTok/issues/227
From what I can gather, the `microtiming_tick_values` attribute was previously only created when calling `_create_base_vocabulary`, which in turn was only called when `len(vocab) == 0` in the base `MusicTokenizer` class, see [this line](https://github.com/Natooz/MidiTok/blob/446c0417eb1851cca2063719f2b14e9b5cfcb867/src/miditok/midi_tokenizer.py#L254). This does not happen when loading a trained PerTok tokenizer as the vocabulary size is already greater than 0.
My fix is simply to move the creation of `microtiming_tick_values` into its own function, then call this at the end of `PerTok.__init__` if `use_microtiming = True` and the attribute hasn't already been set inside `_create_base_vocabulary`. …
=> Bugfix when loading trained `PerTok` tokenizer

src/miditok/tokenizations/pertok.py
This PR fixes a bug in the `PerTok` tokenizer that occurs during decoding (MIDI conversion) when `use_sustain_pedals=True` is set in the tokenizer configuration.
The issue can be reproduced with the following code:
```python
from miditok import PerTok, TokenizerConfig
from symusic import Score
TOKENIZER_PARAMS = {
"pitch_range": (21, 109),
"beat_res": {(0, 4): 4, (0, 4): 3},
"special_tokens": ["PAD", "BOS", "EOS", "MASK"],
"use_chords": False,
"use_rests": False,
"use_tempos": False,
"use_time_signatures": True,
"use_programs": False,
"use_microtiming": True,
"ticks_per_quarter": 320,
"max_microtiming_shift": 0.125,
"num_microtiming_bins": 30,
"use_sustain_pedals": True  # <-- sustain pedal enabled
}
config = TokenizerConfig(**TOKENIZER_PARAMS)
tokenizer = PerTok(config)
midi = …
```
=> Fix error in PerTok decoding (MIDI conversion) when use_sustain_pedals=True

src/miditok/tokenizations/pertok.py
This PR adds an optional flag of `use_position_toks` in the TokenizerConfig. If set to `true`, it replaces all macro timeshift events with Position tokens, similar to REMI. However it retains the core MicroTime functionality for expressive timing. The implementation is backward compatible with previous versions of PerTok, and by default is set to `off`. 
----
📚 Documentation preview 📚: https://miditok--236.org.readthedocs.build/en/236/
=> PerTok: Position tokens instead of Timeshift

src/miditok/tokenizations/pertok.py
If loading a PerTok tokenizer that was pickled before the 'Position toks' changes were introduced, it would fail. This PR fixes it by introducing a basic setstate method to default the Position toks to 'false'
----
📚 Documentation preview 📚: https://miditok--243.org.readthedocs.build/en/243/
=> Fix backwards compatibility with older PerTok versions
